package main

import (
	"strings"

	"github.com/iancoleman/strcase"
	"github.com/takuoki/clmconv"
)

func (g *generator) output(m model, o option) {
	g.outputHeader(m)
	g.outputImport(m)
	g.outputConst(m, o)
	g.outputVar(m)
	g.outputCompileCheck(m, o)
	g.outputInit(m, o)
	g.outputLoad(m)
	g.outputGet(m, o)
	g.outputGetList(m, o)
	g.outputAdd(m, o)
	g.outputUpdate(m, o)
	g.outputDelete(m, o)
	g.outputValidate(m)
	g.outputParse(m)
	g.outputAsync(m, o)
}

func (g *generator) outputHeader(m model) {
	g.Printf("// Code generated by \"sheetdb-modeler\"; DO NOT EDIT.\n")
	g.Printf("// Create a Spreadsheet (sheet name: \"%s\") as data storage.\n", m.NameLowerPlural)
	g.Printf("// The spreadsheet header is as follows:\n")
	g.Printf("//   ")
	for _, f := range m.Fields {
		g.Printf("%s | ", strcase.ToSnake(f.Name))
	}
	g.Printf("updated_at | deleted_at\n")
	g.Printf("// Please copy and paste this header on the first line of the sheet.\n")
	g.Printf("\npackage %s\n\n", g.pkg.name)
}

func (g *generator) outputImport(m model) {

	var needStrconv bool
	for _, f := range m.Fields {
		switch f.TypNonPointer {
		case "bool", "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"float32", "float64":
			needStrconv = true
			break
		}
	}

	g.Printf("import (\n")
	if needStrconv {
		g.Printf("\t\"strconv\"\n")
	}
	g.Printf("\t\"sync\"\n")
	g.Printf("\t\"time\"\n")
	g.Printf("\n")
	g.Printf("\t\"github.com/takuoki/gsheets\"\n")
	g.Printf("\t\"github.com/takuoki/sheetdb\"\n")
	g.Printf(")\n\n")
}

func (g *generator) outputConst(m model, o option) {
	g.Printf("const (\n")
	g.Printf("\t// Sheet definition\n")
	g.Printf("\t_%s_sheetName = \"%s\"\n", m.Name, m.NameLowerPlural)
	for i, f := range m.Fields {
		g.Printf("\t_%s_column_%s = %d // %s\n", m.Name, f.Name, i, clmconv.Itoa(i))
	}
	g.Printf("\t_%s_column_UpdatedAt = %d // %s\n", m.Name, len(m.Fields), clmconv.Itoa(len(m.Fields)))
	g.Printf("\t_%s_column_DeletedAt = %d // %s\n", m.Name, len(m.Fields)+1, clmconv.Itoa(len(m.Fields)+1))

	if m.Parent != nil || len(m.Children) > 0 {
		g.Printf("\t\n// Parent children relation for compile check\n")
		if m.Parent != nil {
			g.Printf("\t_%s_modelSetName_%s = 0\n", m.Name, o.ModelSetName)
		}
		if m.Parent != nil {
			g.Printf("\t_%s_parent_%s = 0\n", m.Name, m.Parent.Name)
		}
		for _, child := range m.DirectChildrenNames {
			g.Printf("\t_%s_child_%s = 0\n", m.Name, child)
		}
		g.Printf("\t_%s_numOfChildren = %d\n", m.Name, len(m.Children))
		g.Printf("\t_%s_numOfDirectChildren = %d\n", m.Name, len(m.DirectChildrenNames))
	}

	if o.TestMode {
		g.Printf("\n\t\n// Output only when test mode\n")
		g.Printf("\tTestMode_%s = 0\n", m.Name)
	}

	g.Printf(")\n\n")
}

func (g *generator) outputVar(m model) {
	g.Printf("var (\n")
	g.Printf("\t_%s_mutex = sync.RWMutex{}\n", m.Name)
	g.Printf("\t_%[1]s_cache = map[%[2]s]*%[1]s{} // map[%[3]s]*%[1]s\n", m.Name, strings.Join(m.PkTypes, "]map["), strings.Join(m.PkNameLowers, "]["))
	g.Printf("\t_%s_rowNoMap = map[%s]int{} // map[%[3]s]rowNo\n", m.Name, strings.Join(m.PkTypes, "]map["), strings.Join(m.PkNameLowers, "]["))
	g.Printf("\t_%s_maxRowNo = 0\n", m.Name)
	for _, f := range m.Fields {
		if f.Unique {
			if m.Parent == nil {
				g.Printf("\t_%[1]s_%[2]s_uniqueMap = map[string]*%[1]s{} // map[%[3]s]*%[1]s\n", m.Name, f.Name, f.NameLower)
			} else {
				g.Printf("\t_%[1]s_%[2]s_uniqueMap = map[%[3]s]map[string]*%[1]s{} // map[%[4]s][%[5]s]*%[1]s\n", m.Name, f.Name,
					strings.Join(m.Parent.PkTypes, "]map["), strings.Join(m.Parent.PkNameLowers, "]["), f.NameLower)
			}
		}
	}
	g.Printf(")\n\n")
}

func (g *generator) outputCompileCheck(m model, o option) {
	if m.Parent == nil && len(m.Children) == 0 {
		return
	}
	g.Printf("func _() {\n")
	if len(m.DirectChildrenNames) > 0 {
		g.Printf("\t// An \"undeclared name\" compiler error signifies that parent and child model set names are different.\n")
		g.Printf("\t// Make sure that all models in parent-child relationship exist in the same model set (spreadsheet) and try again.\n")
		for _, child := range m.DirectChildrenNames {
			g.Printf("\t_ = _%s_modelSetName_%s\n", child, o.ModelSetName)
		}
	}
	g.Printf("\t// An \"undeclared name\" compiler error signifies that parent-children option conflicts between models.\n")
	g.Printf("\t// Make sure that the parent-children options are correct for all relevant models and try again.\n")
	if m.Parent != nil {
		g.Printf("\t_ = _%[2]s_child_%[1]s\n", m.Name, m.Parent.Name)
	}
	for _, child := range m.DirectChildrenNames {
		g.Printf("\t_ = _%[2]s_parent_%[1]s\n", m.Name, child)
	}
	if len(m.Children) > 0 {
		g.Printf("\t// An \"invalid array index\" compiler error signifies that the children option is incorrect.\n")
		g.Printf("\t// Make sure that all child models are specified, including not only the direct child model\n")
		g.Printf("\t// but also the grandchild model, and try again.\n")
		g.Printf("\tvar x [1]struct{}\n")
		g.Printf("\t_ = x[_%[1]s_numOfChildren - _%[1]s_numOfDirectChildren", m.Name)
		for _, child := range m.DirectChildrenNames {
			g.Printf(" - _%s_numOfChildren", child)
		}
		g.Printf("\t]\n")
	}
	g.Printf("}\n\n")
}

func (g *generator) outputInit(m model, o option) {
	g.Printf("func init() {\n")
	g.Printf("\tsheetdb.RegisterModel(\"%[2]s\", \"%[1]s\", _%[1]s_sheetName, _%[1]s_load)\n", m.Name, o.ModelSetName)
	g.Printf("}\n\n")
}

func (g *generator) outputLoad(m model) {
	g.Printf("func _%s_load(data *gsheets.Sheet) error {\n\n", m.Name)

	g.Printf("\t_%s_mutex.Lock()\n", m.Name)
	g.Printf("\tdefer _%s_mutex.Unlock()\n\n", m.Name)

	g.Printf("\t_%[1]s_cache = map[%[2]s]*%[1]s{}\n", m.Name, strings.Join(m.PkTypes, "]map["))
	g.Printf("\t_%s_rowNoMap = map[%s]int{}\n", m.Name, strings.Join(m.PkTypes, "]map["))
	g.Printf("\t_%s_maxRowNo = 0\n", m.Name)
	for _, f := range m.Fields {
		if f.Unique {
			if m.Parent == nil {
				g.Printf("\t_%[1]s_%[2]s_uniqueMap = map[string]*%[1]s{}\n", m.Name, f.Name)
			} else {
				g.Printf("\t_%[1]s_%[2]s_uniqueMap = map[%[3]s]map[string]*%[1]s{}\n", m.Name, f.Name, strings.Join(m.Parent.PkTypes, "]map["))
			}
		}
	}
	g.Printf("\n")

	g.Printf("\tfor i, r := range data.Rows() {\n")
	g.Printf("\t\tif i == 0 {\n")
	g.Printf("\t\t\tcontinue\n")
	g.Printf("\t\t}\n")
	g.Printf("\t\tif r.Value(_%s_column_DeletedAt) != \"\" {\n", m.Name)
	g.Printf("\t\t\t_%s_maxRowNo++\n", m.Name)
	g.Printf("\t\t\tcontinue\n")
	g.Printf("\t\t}\n")
	g.Printf("\t\tif r.Value(_%s_column_%s) == \"\" {\n", m.Name, m.Fields[0].Name)
	g.Printf("\t\t\tbreak\n")
	g.Printf("\t\t}\n\n")

	for _, f := range m.Fields {
		if f.Typ == "string" {
			g.Printf("\t\t%[3]s := r.Value(_%[1]s_column_%[2]s)\n", m.Name, f.Name, f.NameLower)
			if f.Unique {
				if m.Parent == nil {
					g.Printf("\t\tif err := _%[1]s_validate%[2]s(%[3]s, \"\"); err != nil {\n", m.Name, f.Name, f.NameLower)
				} else {
					g.Printf("\t\tif err := _%[1]s_validate%[2]s(%[3]s, %[4]s, \"\"); err != nil {\n", m.Name, f.Name, f.NameLower, strings.Join(m.Parent.PkNameLowers, ", "))
				}
			} else {
				g.Printf("\t\tif err := _%[1]s_validate%[2]s(%[3]s); err != nil {\n", m.Name, f.Name, f.NameLower)
			}
		} else {
			g.Printf("\t\t%[3]s, err := _%[1]s_parse%[2]s(r.Value(_%[1]s_column_%[2]s))\n", m.Name, f.Name, f.NameLower)
			g.Printf("\t\tif err != nil {\n")
		}
		g.Printf("\t\t\treturn err\n")
		g.Printf("\t\t}\n")
	}
	g.Printf("\n")

	g.Printf("\t\tif _, ok := _%[1]s_cache[%[2]s]; ok {\n", m.Name, strings.Join(m.PkNameLowers, "]["))
	g.Printf("\t\t\treturn &sheetdb.DuplicationError{FieldName: \"%s\"}\n", m.ThisKeyName)
	g.Printf("\t\t}\n\n")

	g.Printf("\t\t%[2]s := %[1]s{\n", m.Name, m.NameLower)
	for _, f := range m.Fields {
		g.Printf("\t\t\t%s: %s,\n", f.Name, f.NameLower)
	}
	g.Printf("\t\t}\n\n")

	g.Printf("\t\t_%s_maxRowNo++\n", m.Name)
	g.outputParentMap(m)
	g.Printf("\t\t_%[1]s_cache[%[3]s] = &%[2]s\n", m.Name, m.NameLower, strings.Join(prefixes(m.PkNames, m.NameLower+"."), "]["))
	g.Printf("\t\t_%[1]s_rowNoMap[%[2]s] = _%[1]s_maxRowNo\n", m.Name, strings.Join(prefixes(m.PkNames, m.NameLower+"."), "]["))
	for _, f := range m.Fields {
		if f.Unique {
			if m.Parent == nil {
				g.Printf("\t\t_%[1]s_%[2]s_uniqueMap[%[3]s.%[2]s] = &%[3]s\n", m.Name, f.Name, m.NameLower)
			} else {
				g.Printf("\t\t_%[1]s_%[2]s_uniqueMap[%[4]s][%[3]s.%[2]s] = &%[3]s\n", m.Name, f.Name, m.NameLower, strings.Join(prefixes(m.Parent.PkNames, m.NameLower+"."), "]["))
			}
		}
	}
	g.Printf("\t}\n\n")

	g.Printf("\treturn nil\n")
	g.Printf("}\n\n")
}

func (g *generator) outputParentMap(m model) {
	for i := 0; i < len(m.PkNames)-1; i++ {
		g.Printf("if _, ok := _%[1]s_cache[%[2]s]; !ok {\n", m.Name,
			strings.Join(prefixes(m.PkNames[:i+1], m.NameLower+"."), "]["))
		g.Printf("\t_%[1]s_cache[%[2]s] = map[%[3]s]*%[1]s{}\n", m.Name,
			strings.Join(prefixes(m.PkNames[:i+1], m.NameLower+"."), "]["),
			strings.Join(m.PkTypes[i+1:], "]map["))
		g.Printf("\t	_%[1]s_rowNoMap[%[2]s] = map[%[3]s]int{}\n", m.Name,
			strings.Join(prefixes(m.PkNames[:i+1], m.NameLower+"."), "]["),
			strings.Join(m.PkTypes[i+1:], "]map["))
		if m.Parent != nil {
			for _, f := range m.Fields {
				if f.Unique {
					if i < len(m.PkNames)-2 {
						g.Printf("\t_%[1]s_%[2]s_uniqueMap[%[3]s] = map[%[4]s]map[string]*%[1]s{}\n", m.Name, f.Name,
							strings.Join(prefixes(m.PkNames[:i+1], m.NameLower+"."), "]["),
							strings.Join(m.Parent.PkTypes[i+1:], "]map["))
					} else {
						g.Printf("\t_%[1]s_%[2]s_uniqueMap[%[3]s] = map[string]*%[1]s{}\n", m.Name, f.Name,
							strings.Join(prefixes(m.PkNames[:i+1], m.NameLower+"."), "]["))
					}
				}
			}
		}
		g.Printf("}\n")
	}
}

func (g *generator) outputGet(m model, o option) {

	method := "Get"
	if o.Private {
		method = "get"
	}

	g.Printf("// %[4]s%[1]s returns a %[2]s by %[3]s.\n", m.Name, m.NameLower, m.ThisKeyName, method)
	if m.Parent == nil {
		g.Printf("// If it can not be found, this function returns *sheetdb.NotFoundError.\n")
		g.Printf("func %[3]s%[1]s(%[2]s) (*%[1]s, error) {\n", m.Name, join(m.PkNameLowers, m.PkTypes, " ", ", "), method)
	} else {
		g.Printf("// If it can not be found, this method returns *sheetdb.NotFoundError.\n")
		g.Printf("func (m *%[2]s) %[5]s%[1]s(%[3]s %[4]s) (*%[1]s, error) {\n", m.Name, m.Parent.Name, m.ThisKeyNameLower, m.ThisKeyType, method)
	}

	g.Printf("\t_%s_mutex.RLock()\n", m.Name)
	g.Printf("\tdefer _%s_mutex.RUnlock()\n", m.Name)

	if m.Parent == nil {
		g.Printf("\tif v, ok := _%s_cache[%s]; ok {\n", m.Name, m.ThisKeyNameLower)
	} else {
		g.Printf("\tif v, ok := _%s_cache[%s][%s]; ok {\n", m.Name, strings.Join(prefixes(m.Parent.PkNames, "m."), "]["), m.ThisKeyNameLower)
	}

	g.Printf("\t\treturn v, nil\n")
	g.Printf("\t}\n")
	g.Printf("\treturn nil, &sheetdb.NotFoundError{Model: \"%s\"}\n", m.Name)
	g.Printf("}\n\n")

	if m.Parent != nil {
		g.Printf("// %[3]s%[1]s returns a %[2]s by primary keys.\n", m.Name, m.NameLower, method)
		g.Printf("// If it can not be found, this function returns *sheetdb.NotFoundError.\n")
		g.Printf("func %[3]s%[1]s(%[2]s) (*%[1]s, error) {\n", m.Name, join(m.PkNameLowers, m.PkTypes, " ", ", "), method)
		g.outputGetParent(*m.Parent, o, true, 0)
		g.Printf("\treturn m.%[3]s%[1]s(%[2]s)\n", m.Name, m.ThisKeyNameLower, method)
		g.Printf("}\n\n")
	}

	for _, f := range m.Fields {
		if f.Unique {
			if m.Parent == nil {
				g.Printf("// %[4]s%[1]sBy%[3]s returns a %[2]s by %[3]s.\n", m.Name, m.NameLower, f.Name, method)
				g.Printf("// If it can not be found, this function returns *sheetdb.NotFoundError.\n")
				g.Printf("func %[4]s%[1]sBy%[2]s(%[3]s string) (*%[1]s, error) {\n", m.Name, f.Name, f.NameLower, method)
				g.Printf("\t_%s_mutex.RLock()\n", m.Name)
				g.Printf("\tdefer _%s_mutex.RUnlock()\n", m.Name)
				g.Printf("\tif v, ok := _%s_%s_uniqueMap[%s]; ok {\n", m.Name, f.Name, f.NameLower)
				g.Printf("\t\treturn v, nil\n")
				g.Printf("\t}\n")
				g.Printf("\treturn nil, &sheetdb.NotFoundError{Model: \"%s\"}\n", m.Name)
				g.Printf("}\n\n")
			} else {
				g.Printf("// %[4]s%[1]sBy%[3]s returns a %[2]s by %[3]s.\n", m.Name, m.NameLower, f.Name, method)
				g.Printf("// If it can not be found, this method returns *sheetdb.NotFoundError.\n")
				g.Printf("func (m *%[4]s) %[5]s%[1]sBy%[2]s(%[3]s string) (*%[1]s, error) {\n", m.Name, f.Name, f.NameLower, m.Parent.Name, method)
				g.Printf("\t_%s_mutex.RLock()\n", m.Name)
				g.Printf("\tdefer _%s_mutex.RUnlock()\n", m.Name)
				g.Printf("\tif v, ok := _%[1]s_%[2]s_uniqueMap[%[4]s][%[3]s]; ok {\n", m.Name, f.Name, f.NameLower, strings.Join(prefixes(m.Parent.PkNames, "m."), "]["))
				g.Printf("\t\treturn v, nil\n")
				g.Printf("\t}\n")
				g.Printf("\treturn nil, &sheetdb.NotFoundError{Model: \"%s\"}\n", m.Name)
				g.Printf("}\n\n")

				g.Printf("// %[4]s%[1]sBy%[3]s returns a %[2]s by %[3]s.\n", m.Name, m.NameLower, f.Name, method)
				g.Printf("// If it can not be found, this function returns *sheetdb.NotFoundError.\n")
				g.Printf("func %[5]s%[1]sBy%[2]s(%[4]s, %[3]s string) (*%[1]s, error) {\n", m.Name, f.Name, f.NameLower, join(m.Parent.PkNameLowers, m.Parent.PkTypes, " ", ", "), method)
				g.outputGetParent(*m.Parent, o, true, 0)
				g.Printf("\treturn m.%[4]s%[1]sBy%[2]s(%[3]s)\n", m.Name, f.Name, f.NameLower, method)
				g.Printf("}\n\n")
			}
		}
	}
}

func (g *generator) outputGetParent(m model, o option, returnNil bool, i int) {

	method := "Get"
	if o.Private {
		method = "get"
	}

	if m.Parent != nil {
		g.outputGetParent(*m.Parent, o, returnNil, i+1)
	}
	if i == 0 {
		g.Printf("\tm, err := %[3]s%[1]s(%[2]s)\n", m.Name, strings.Join(m.PkNameLowers, ", "), method)
	} else {
		g.Printf("\tm%[3]d, err := %[4]s%[1]s(%[2]s)\n", m.Name, strings.Join(m.PkNameLowers, ", "), i, method)
	}
	g.Printf("\tif err != nil {\n")
	if returnNil {
		g.Printf("\t\treturn nil, err\n")
	} else {
		g.Printf("\t\treturn err\n")
	}
	g.Printf("\t}\n")
}

func (g *generator) outputGetList(m model, o option) {

	method := "Get"
	modelName := m.Name
	if o.Private {
		method = "get"
		modelName = m.NameLower
	}

	g.Printf("// %sQuery is used for selecting %s.\n", modelName, m.NameLowerPlural)
	g.Printf("type %sQuery struct {\n", modelName)
	g.Printf("\tfilter func(%[2]s *%[1]s) bool\n", m.Name, m.NameLower)
	g.Printf("\tsort   func(%[2]s []*%[1]s)\n", m.Name, m.NameLowerPlural)
	g.Printf("}\n\n")

	g.Printf("// %[1]sQueryOption is an option to change the behavior of %[1]sQuery.\n", modelName)
	g.Printf("type %[1]sQueryOption func(query *%[1]sQuery) *%[1]sQuery\n\n", modelName)

	g.Printf("// %[1]sFilter is an option to change the filtering behavior of %[1]sQuery.\n", modelName)
	g.Printf("func %[1]sFilter(filterFunc func(%[3]s *%[2]s) bool) func(query *%[1]sQuery) *%[1]sQuery {\n", modelName, m.Name, m.NameLower)
	g.Printf("\treturn func(query *%[1]sQuery) *%[1]sQuery {\n", modelName)
	g.Printf("\t\tif query != nil {\n")
	g.Printf("\t\t\tquery.filter = filterFunc\n")
	g.Printf("\t\t}\n")
	g.Printf("\t\treturn query\n")
	g.Printf("\t}\n")
	g.Printf("}\n\n")

	g.Printf("// %[1]sSort is an option to change the sorting behavior of %[1]sQuery.\n", modelName)
	g.Printf("func %[1]sSort(sortFunc func(%[3]s []*%[2]s)) func(query *%[1]sQuery) *%[1]sQuery {\n", modelName, m.Name, m.NameLowerPlural)
	g.Printf("\treturn func(query *%[1]sQuery) *%[1]sQuery {\n", modelName)
	g.Printf("\t\tif query != nil {\n")
	g.Printf("\t\t\tquery.sort = sortFunc\n")
	g.Printf("\t\t}\n")
	g.Printf("\t\treturn query\n")
	g.Printf("\t}\n")
	g.Printf("}\n\n")

	if m.Parent == nil {
		g.Printf("// %[3]s%[1]s returns all %[2]s.\n", m.NamePlural, m.NameLowerPlural, method)
		g.Printf("// If any options are specified, the result according to the specified option is returned.\n")
		g.Printf("// If there are no %s to return, this function returns an nil array.\n", m.NameLower)
		g.Printf("// If the sort option is not specified, the order of %s is random.\n", m.NameLowerPlural)
		g.Printf("func %[4]s%[3]s(opts ...%[1]sQueryOption) ([]*%[2]s, error) {\n", modelName, m.Name, m.NamePlural, method)
	} else {
		g.Printf("// %[4]s%[1]s returns all %[2]s that %[3]s has.\n", m.NamePlural, m.NameLowerPlural, m.Parent.NameLower, method)
		g.Printf("// If any options are specified, the result according to the specified option is returned.\n")
		g.Printf("// If there are no %s to return, this method returns an nil array.\n", m.NameLower)
		g.Printf("// If the sort option is not specified, the order of %s is random.\n", m.NameLowerPlural)
		g.Printf("func (m *%[4]s) %[5]s%[3]s(opts ...%[1]sQueryOption) ([]*%[2]s, error) {\n", modelName, m.Name, m.NamePlural, m.Parent.Name, method)
	}

	g.Printf("\tquery := &%[1]sQuery{}\n", modelName)
	g.Printf("\tfor _, opt := range opts {\n")
	g.Printf("\t\tquery = opt(query)\n")
	g.Printf("\t}\n")
	g.Printf("\t_%s_mutex.RLock()\n", m.Name)
	g.Printf("\tdefer _%s_mutex.RUnlock()\n", m.Name)
	g.Printf("\tvar %[2]s []*%[1]s\n", m.Name, m.NameLowerPlural)
	g.Printf("\tif query.filter != nil {\n")

	if m.Parent == nil {
		g.Printf("\t\tfor _, v := range _%s_cache {\n", m.Name)
	} else {
		g.Printf("\t\tfor _, v := range _%s_cache[%s] {\n", m.Name, strings.Join(prefixes(m.Parent.PkNames, "m."), "]["))
	}

	g.Printf("\t\t\tif query.filter(v) {\n")
	g.Printf("\t\t\t\t%[1]s = append(%[1]s, v)\n", m.NameLowerPlural)
	g.Printf("\t\t\t}\n")
	g.Printf("\t\t}\n")
	g.Printf("\t} else {\n")

	if m.Parent == nil {
		g.Printf("\t\tfor _, v := range _%s_cache {\n", m.Name)
	} else {
		g.Printf("\t\tfor _, v := range _%s_cache[%s] {\n", m.Name, strings.Join(prefixes(m.Parent.PkNames, "m."), "]["))
	}

	g.Printf("\t\t\t%[1]s = append(%[1]s, v)\n", m.NameLowerPlural)
	g.Printf("\t\t}\n")
	g.Printf("\t}\n")
	g.Printf("\tif query.sort != nil {\n")
	g.Printf("\t\tquery.sort(%s)\n", m.NameLowerPlural)
	g.Printf("\t}\n")
	g.Printf("\treturn %s, nil\n", m.NameLowerPlural)
	g.Printf("}\n\n")

	if m.Parent != nil {
		g.Printf("// %[4]s%[1]s returns all %[2]s that %[3]s has.\n", m.NamePlural, m.NameLowerPlural, m.Parent.NameLower, method)
		g.Printf("// If any options are specified, the result according to the specified option is returned.\n")
		g.Printf("// If there are no %s to return, this function returns an nil array.\n", m.NameLower)
		g.Printf("// If the sort option is not specified, the order of %s is random.\n", m.NameLowerPlural)
		g.Printf("func %[5]s%[3]s(%[4]s, opts ...%[1]sQueryOption) ([]*%[2]s, error) {\n", modelName, m.Name, m.NamePlural, join(m.Parent.PkNameLowers, m.Parent.PkTypes, " ", ", "), method)
		g.outputGetParent(*m.Parent, o, true, 0)
		g.Printf("\treturn m.%[2]s%[1]s(opts...)\n", m.NamePlural, method)
		g.Printf("}\n\n")
	}
}

func (g *generator) outputAdd(m model, o option) {

	method := "Add"
	if o.Private {
		method = "add"
	}

	if m.Parent == nil {
		g.Printf("// %[3]s%[1]s adds new %[2]s.\n", m.Name, m.NameLower, method)
		if autoNumbering(m.ThisKeyName, m.ThisKeyType) {
			g.Printf("// %s is generated automatically.\n", m.ThisKeyName)
			g.Printf("// If any fields are invalid, this function returns error.\n")
			g.Printf("func %[3]s%[1]s(%[2]s) (*%[1]s, error) {\n", m.Name, join(m.NonPkNameLowers, m.NonPkTypes, " ", ", "), method)
		} else {
			g.Printf("// If argument '%s' already exist, this function returns *sheetdb.DuplicationError.\n", m.ThisKeyNameLower)
			g.Printf("// If any fields are invalid, this function returns error.\n")
			g.Printf("func %[5]s%[1]s(%[2]s %[3]s, %[4]s) (*%[1]s, error) {\n", m.Name, m.ThisKeyNameLower, m.ThisKeyType, join(m.NonPkNameLowers, m.NonPkTypes, " ", ", "), method)
		}
	} else {
		g.Printf("// %[4]s%[1]s adds new %[2]s to %[3]s.\n", m.Name, m.NameLower, m.Parent.NameLower, method)
		if autoNumbering(m.ThisKeyName, m.ThisKeyType) {
			g.Printf("// %s is generated automatically.\n", m.ThisKeyName)
			g.Printf("// If any fields are invalid, this method returns error.\n")
			g.Printf("func (m *%[2]s) %[4]s%[1]s(%[3]s) (*%[1]s, error) {\n", m.Name, m.Parent.Name, join(m.NonPkNameLowers, m.NonPkTypes, " ", ", "), method)
		} else {
			g.Printf("// If argument '%s' already exists in this %s, this method returns *sheetdb.DuplicationError.\n", m.ThisKeyNameLower, m.Parent.NameLower)
			g.Printf("// If any fields are invalid, this method returns error.\n")
			g.Printf("func (m *%[4]s) %[6]s%[1]s(%[2]s %[3]s, %[5]s) (*%[1]s, error) {\n", m.Name, m.ThisKeyNameLower, m.ThisKeyType, m.Parent.Name, join(m.NonPkNameLowers, m.NonPkTypes, " ", ", "), method)
		}
	}

	g.Printf("\t_%s_mutex.Lock()\n", m.Name)
	g.Printf("\tdefer _%s_mutex.Unlock()\n", m.Name)

	if !autoNumbering(m.ThisKeyName, m.ThisKeyType) {
		if m.Parent == nil {
			g.Printf("\tif _, ok := _%[1]s_cache[%[2]s]; ok {\n", m.Name, strings.Join(m.PkNameLowers, "]["))
		} else {
			g.Printf("\tif _, ok := _%[1]s_cache[%[2]s][%[3]s]; ok {\n", m.Name, strings.Join(prefixes(m.Parent.PkNames, "m."), "]["), m.ThisKeyNameLower)
		}
		g.Printf("\t\treturn nil, &sheetdb.DuplicationError{FieldName: \"%s\"}\n", m.ThisKeyName)
		g.Printf("\t}\n")
	}

	for _, f := range m.Fields {
		if !f.IsPk && f.Typ == "string" {
			if f.Unique {
				if m.Parent == nil {
					g.Printf("\tif err := _%[1]s_validate%[2]s(%[3]s, \"\"); err != nil {\n", m.Name, f.Name, f.NameLower)
				} else {
					g.Printf("\tif err := _%[1]s_validate%[2]s(%[3]s, %[4]s, \"\"); err != nil {\n", m.Name, f.Name, f.NameLower, strings.Join(prefixes(m.Parent.PkNames, "m."), ", "))
				}
				g.Printf("\t\treturn nil, err\n")
				g.Printf("\t}\n")
			} else {
				g.Printf("\tif err := _%[1]s_validate%[2]s(%[3]s); err != nil {\n", m.Name, f.Name, f.NameLower)
				g.Printf("\t\treturn nil, err\n")
				g.Printf("\t}\n")
			}
		}
	}

	if m.Parent != nil && autoNumbering(m.ThisKeyName, m.ThisKeyType) {
		g.Printf("\tmaxID := 0\n")
		g.Printf("\tfor _, v := range _%[1]s_cache[%[2]s] {\n", m.Name, strings.Join(prefixes(m.Parent.PkNames, "m."), "]["))
		g.Printf("\t\tif maxID < v.%s {\n", m.ThisKeyName)
		g.Printf("\t\t\tmaxID = v.%s\n", m.ThisKeyName)
		g.Printf("\t\t}\n")
		g.Printf("\t}\n")
	}

	g.Printf("\t%[2]s := &%[1]s{\n", m.Name, m.NameLower)

	for _, f := range m.Fields {
		if f.IsPk {
			if f.IsParentKey {
				g.Printf("\t\t%[1]s: m.%[1]s,\n", f.Name)
			} else if autoNumbering(f.Name, f.Typ) {
				if m.Parent == nil {
					g.Printf("\t\t%[2]s: _%[1]s_maxRowNo + %[3]d,\n", m.Name, f.Name, o.Initial)
				} else {
					g.Printf("\t\t%[1]s: maxID + %[2]d,\n", f.Name, o.Initial)
				}
			} else {
				g.Printf("\t\t%s: %s,\n", f.Name, f.NameLower)
			}
		} else {
			g.Printf("\t\t%s: %s,\n", f.Name, f.NameLower)
		}
	}

	g.Printf("\t}\n")
	g.Printf("\tif err := %[2]s._asyncAdd(_%[1]s_maxRowNo + 1); err != nil {\n", m.Name, m.NameLower)
	g.Printf("\t\treturn nil, err\n")
	g.Printf("\t}\n")
	g.Printf("\t_%s_maxRowNo++\n", m.Name)

	g.outputParentMap(m)

	g.Printf("\t_%[1]s_cache[%[3]s] = %[2]s\n", m.Name, m.NameLower, strings.Join(prefixes(m.PkNames, m.NameLower+"."), "]["))
	g.Printf("\t_%[1]s_rowNoMap[%[2]s] = _%[1]s_maxRowNo\n", m.Name, strings.Join(prefixes(m.PkNames, m.NameLower+"."), "]["))
	for _, f := range m.Fields {
		if f.Unique {
			if m.Parent == nil {
				g.Printf("\t_%[1]s_%[2]s_uniqueMap[%[3]s.%[2]s] = %[3]s\n", m.Name, f.Name, m.NameLower)
			} else {
				g.Printf("\t_%[1]s_%[2]s_uniqueMap[%[4]s][%[3]s.%[2]s] = %[3]s\n", m.Name, f.Name, m.NameLower, strings.Join(prefixes(m.Parent.PkNames, m.NameLower+"."), "]["))
			}
		}
	}
	g.Printf("\treturn %s, nil\n", m.NameLower)
	g.Printf("}\n\n")

	if m.Parent != nil {
		g.Printf("// %[4]s%[1]s adds new %[2]s to %[3]s.\n", m.Name, m.NameLower, m.Parent.NameLower, method)
		if autoNumbering(m.ThisKeyName, m.ThisKeyType) {
			g.Printf("// %s is generated automatically.\n", m.ThisKeyName)
			g.Printf("// If any fields are invalid, this function returns error.\n")
			g.Printf("func %[4]s%[1]s(%[2]s, %[3]s) (*%[1]s, error) {\n", m.Name, join(m.Parent.PkNameLowers, m.Parent.PkTypes, " ", ", "), join(m.NonPkNameLowers, m.NonPkTypes, " ", ", "), method)
		} else {
			g.Printf("// If primary keys already exist, this function returns *sheetdb.DuplicationError.\n")
			g.Printf("// If any fields are invalid, this function returns error.\n")
			g.Printf("func %[3]s%[1]s(%[2]s) (*%[1]s, error) {\n", m.Name, join(m.FieldNameLowers, m.FieldTypes, " ", ", "), method)
		}
		g.outputGetParent(*m.Parent, o, true, 0)
		if autoNumbering(m.ThisKeyName, m.ThisKeyType) {
			g.Printf("\treturn m.%[3]s%[1]s(%[2]s)\n", m.Name, strings.Join(m.NonPkNameLowers, ", "), method)
		} else {
			g.Printf("\treturn m.%[4]s%[1]s(%[2]s, %[3]s)\n", m.Name, m.ThisKeyNameLower, strings.Join(m.NonPkNameLowers, ", "), method)
		}
		g.Printf("}\n\n")
	}
}

func (g *generator) outputUpdate(m model, o option) {

	method := "Update"
	if o.Private {
		method = "update"
	}

	if m.Parent == nil {
		g.Printf("// %[3]s%[1]s updates %[2]s.\n", m.Name, m.NameLower, method)
		g.Printf("// If it can not be found, this function returns *sheetdb.NotFoundError.\n")
		g.Printf("// If any fields are invalid, this function returns error.\n")
		g.Printf("func %[3]s%[1]s(%[2]s) (*%[1]s, error) {\n", m.Name, join(m.FieldNameLowers, m.FieldTypes, " ", ", "), method)
	} else {
		g.Printf("// %[3]s%[1]s updates %[2]s.\n", m.Name, m.NameLower, method)
		g.Printf("// If it can not be found, this method returns *sheetdb.NotFoundError.\n")
		g.Printf("// If any fields are invalid, this method returns error.\n")
		g.Printf("func (m *%[2]s) %[6]s%[1]s(%[3]s %[4]s, %[5]s) (*%[1]s, error) {\n", m.Name, m.Parent.Name, m.ThisKeyNameLower, m.ThisKeyType, join(m.NonPkNameLowers, m.NonPkTypes, " ", ", "), method)
	}

	g.Printf("\t_%s_mutex.Lock()\n", m.Name)
	g.Printf("\tdefer _%s_mutex.Unlock()\n", m.Name)

	if m.Parent == nil {
		g.Printf("\t%[2]s, ok := _%[1]s_cache[%[3]s]\n", m.Name, m.NameLower, m.ThisKeyNameLower)
	} else {
		g.Printf("\t%[2]s, ok := _%[1]s_cache[%[3]s][%[4]s]\n", m.Name, m.NameLower, strings.Join(prefixes(m.Parent.PkNames, "m."), "]["), m.ThisKeyNameLower)
	}

	g.Printf("\tif !ok {\n")
	g.Printf("\t\treturn nil, &sheetdb.NotFoundError{Model: \"%s\"}\n", m.Name)
	g.Printf("\t}\n")

	for _, f := range m.Fields {
		if !f.IsPk && f.Typ == "string" {
			if f.Unique {
				if m.Parent == nil {
					g.Printf("\tif err := _%[1]s_validate%[3]s(%[4]s, %[2]s.%[3]s); err != nil {\n", m.Name, m.NameLower, f.Name, f.NameLower)
				} else {
					g.Printf("\tif err := _%[1]s_validate%[3]s(%[4]s, %[5]s, %[2]s.%[3]s); err != nil {\n", m.Name, m.NameLower, f.Name, f.NameLower, strings.Join(prefixes(m.Parent.PkNames, "m."), ", "))
				}
			} else {
				g.Printf("\tif err := _%[1]s_validate%[2]s(%[3]s); err != nil {\n", m.Name, f.Name, f.NameLower)
			}
			g.Printf("\t\treturn nil, err\n")
			g.Printf("\t}\n")
		}
	}

	g.Printf("\t%[1]sCopy := *%[1]s\n", m.NameLower)

	for _, f := range m.Fields {
		if !f.IsPk {
			g.Printf("\t%sCopy.%s = %s\n", m.NameLower, f.Name, f.NameLower)
		}
	}

	g.Printf("\tif err := (&%sCopy)._asyncUpdate(); err != nil {\n", m.NameLower)
	g.Printf("\t\treturn nil, err\n")
	g.Printf("\t}\n")

	for _, f := range m.Fields {
		if f.Unique {
			g.Printf("\tif %[1]sCopy.%[2]s != %[1]s.%[2]s {\n", m.NameLower, f.Name)
			if m.Parent == nil {
				g.Printf("\t\tdelete(_%[1]s_%[3]s_uniqueMap, %[2]s.%[3]s)\n", m.Name, m.NameLower, f.Name)
			} else {
				g.Printf("\t\tdelete(_%[1]s_%[3]s_uniqueMap[%[4]s], %[2]s.%[3]s)\n", m.Name, m.NameLower, f.Name, strings.Join(prefixes(m.Parent.PkNames, "m."), "]["))
			}
			g.Printf("\t}\n")
		}
	}

	g.Printf("\t*%[1]s = %[1]sCopy\n", m.NameLower)
	for _, f := range m.Fields {
		if f.Unique {
			if m.Parent == nil {
				g.Printf("\t_%[1]s_%[3]s_uniqueMap[%[2]sCopy.%[3]s] = &%[2]sCopy\n", m.Name, m.NameLower, f.Name)
			} else {
				g.Printf("\t_%[1]s_%[3]s_uniqueMap[%[4]s][%[2]sCopy.%[3]s] = &%[2]sCopy\n", m.Name, m.NameLower, f.Name, strings.Join(prefixes(m.Parent.PkNames, "m."), "]["))
			}
		}
	}
	g.Printf("\treturn %s, nil\n", m.NameLower)
	g.Printf("}\n\n")

	if m.Parent != nil {
		g.Printf("// %[3]s%[1]s updates %[2]s.\n", m.Name, m.NameLower, method)
		g.Printf("// If it can not be found, this function returns *sheetdb.NotFoundError.\n")
		g.Printf("// If any fields are invalid, this function returns error.\n")
		g.Printf("func %[3]s%[1]s(%[2]s) (*%[1]s, error) {\n", m.Name, join(m.FieldNameLowers, m.FieldTypes, " ", ", "), method)
		g.outputGetParent(*m.Parent, o, true, 0)
		g.Printf("\treturn m.%[4]s%[1]s(%[2]s, %[3]s)\n", m.Name, m.ThisKeyNameLower, strings.Join(m.NonPkNameLowers, ", "), method)
		g.Printf("}\n\n")
	}
}

func (g *generator) outputDelete(m model, o option) {

	method := "Delete"
	if o.Private {
		method = "delete"
	}

	if m.Parent == nil {
		if len(m.Children) == 0 {
			g.Printf("// %[3]s%[1]s deletes %[2]s.\n", m.Name, m.NameLower, method)
		} else if len(m.Children) == 1 {
			g.Printf("// %[4]s%[1]s deletes %[2]s and it's children %[3]s.\n", m.Name, m.NameLower, m.ChildrenNameLowers[0], method)
		} else {
			g.Printf("// %[5]s%[1]s deletes %[2]s and it's children %[3]s and %[4]s.\n", m.Name, m.NameLower, strings.Join(m.ChildrenNameLowers[:len(m.Children)-1], ", "), m.ChildrenNameLowers[len(m.Children)-1], method)
		}
		g.Printf("// If it can not be found, this function returns *sheetdb.NotFoundError.\n")
		g.Printf("func %[4]s%[1]s(%[2]s %[3]s) error {\n", m.Name, m.ThisKeyNameLower, m.ThisKeyType, method)
	} else {
		if len(m.Children) == 0 {
			g.Printf("// %[4]s%[1]s deletes %[2]s from %[3]s.\n", m.Name, m.NameLower, m.Parent.NameLower, method)
		} else if len(m.Children) == 1 {
			g.Printf("// %[5]s%[1]s deletes %[2]s and it's children %[4]s from %[3]s.\n", m.Name, m.NameLower, m.Parent.NameLower, m.ChildrenNameLowers[0], method)
		} else {
			g.Printf("// %[6]s%[1]s deletes %[2]s and it's children %[4]s and %[5]s from %[3]s.\n", m.Name, m.NameLower, m.Parent.NameLower, strings.Join(m.ChildrenNameLowers[:len(m.Children)-1], ", "), m.ChildrenNameLowers[len(m.Children)-1], method)
		}
		g.Printf("// If it can not be found, this method returns *sheetdb.NotFoundError.\n")
		g.Printf("func (m *%[2]s) %[5]s%[1]s(%[3]s %[4]s) error {\n", m.Name, m.Parent.Name, m.ThisKeyNameLower, m.ThisKeyType, method)
	}

	g.Printf("\t_%s_mutex.Lock()\n", m.Name)
	g.Printf("\tdefer _%s_mutex.Unlock()\n", m.Name)

	for _, child := range m.Children {
		g.Printf("\t_%s_mutex.Lock()\n", child.Name)
		g.Printf("\tdefer _%s_mutex.Unlock()\n", child.Name)
	}

	if m.Parent == nil {
		g.Printf("\t%[2]s, ok := _%[1]s_cache[%[3]s]\n", m.Name, m.NameLower, m.ThisKeyNameLower)
	} else {
		g.Printf("\t%[2]s, ok := _%[1]s_cache[%[3]s][%[4]s]\n", m.Name, m.NameLower, strings.Join(prefixes(m.Parent.PkNames, "m."), "]["), m.ThisKeyNameLower)
	}

	g.Printf("\tif !ok {\n")
	g.Printf("\t\treturn &sheetdb.NotFoundError{Model: \"%s\"}\n", m.Name)
	g.Printf("\t}\n")

	for _, child := range m.Children {
		g.Printf("\tvar %[2]s []*%[1]s\n", child.Name, child.NameLowerPlural)
		if m.Parent == nil {
			g.Printf("\tfor _, v := range _%[1]s_cache[%[2]s] {\n", child.Name, m.ThisKeyNameLower)
		} else {
			g.Printf("\tfor _, v := range _%[1]s_cache[%[2]s][%[3]s] {\n", child.Name, strings.Join(prefixes(m.Parent.PkNames, "m."), "]["), m.ThisKeyNameLower)
		}
		for i := 0; i < len(child.PkNames)-len(m.PkNames)-1; i++ {
			g.Printf("\tfor _, v := range v {\n")
		}
		g.Printf("\t\t%[1]s = append(%[1]s, v)\n", child.NameLowerPlural)
		for i := 0; i < len(child.PkNames)-len(m.PkNames)-1; i++ {
			g.Printf("\t}\n")
		}
		g.Printf("\t}\n")
	}

	g.Printf("\tif err := %s._asyncDelete(%s); err != nil {\n", m.NameLower, strings.Join(m.ChildrenNameLowerPlurals, ", "))
	g.Printf("\t\treturn err\n")
	g.Printf("\t}\n")

	if m.Parent == nil {
		g.Printf("\tdelete(_%[1]s_cache, %[2]s)\n", m.Name, m.ThisKeyNameLower)
	} else {
		g.Printf("\tdelete(_%[1]s_cache[%[3]s], %[2]s)\n", m.Name, m.ThisKeyNameLower, strings.Join(prefixes(m.Parent.PkNames, "m."), "]["))
	}
	for _, f := range m.Fields {
		if f.Unique {
			if m.Parent == nil {
				g.Printf("\tdelete(_%[1]s_%[3]s_uniqueMap, %[2]s.%[3]s)\n", m.Name, m.NameLower, f.Name)
			} else {
				g.Printf("\tdelete(_%[1]s_%[3]s_uniqueMap[%[4]s], %[2]s.%[3]s)\n", m.Name, m.NameLower, f.Name, strings.Join(prefixes(m.Parent.PkNames, "m."), "]["))
			}
		}
	}
	for _, child := range m.Children {
		if m.Parent == nil {
			g.Printf("\tdelete(_%[1]s_cache, %[2]s)\n", child.Name, m.ThisKeyNameLower)
			for _, f := range child.UniqueKeyNames {
				g.Printf("\tdelete(_%[1]s_%[2]s_uniqueMap, %[3]s)\n", child.Name, f, m.ThisKeyNameLower)
			}
		} else {
			g.Printf("\tdelete(_%[1]s_cache[%[3]s], %[2]s)\n", child.Name, m.ThisKeyNameLower, strings.Join(prefixes(m.Parent.PkNames, "m."), "]["))
			for _, f := range child.UniqueKeyNames {
				g.Printf("\tdelete(_%[1]s_%[2]s_uniqueMap[%[4]s], %[3]s)\n", child.Name, f, m.ThisKeyNameLower, strings.Join(prefixes(m.Parent.PkNames, "m."), "]["))
			}
		}
	}

	g.Printf("\treturn nil\n")
	g.Printf("}\n\n")

	if m.Parent != nil {
		if len(m.Children) == 0 {
			g.Printf("// %[4]s%[1]s deletes %[2]s from %[3]s.\n", m.Name, m.NameLower, m.Parent.NameLower, method)
		} else if len(m.Children) == 1 {
			g.Printf("// %[5]s%[1]s deletes %[2]s and it's children %[4]s from %[3]s.\n", m.Name, m.NameLower, m.Parent.NameLower, m.ChildrenNameLowers[0], method)
		} else {
			g.Printf("// %[6]s%[1]s deletes %[2]s and it's children %[4]s and %[5]s from %[3]s.\n", m.Name, m.NameLower, m.Parent.NameLower, strings.Join(m.ChildrenNameLowers[:len(m.Children)-1], ", "), m.ChildrenNameLowers[len(m.Children)-1], method)
		}
		g.Printf("// If it can not be found, this function returns *sheetdb.NotFoundError.\n")

		g.Printf("func %[3]s%[1]s(%[2]s) error {\n", m.Name, join(m.PkNameLowers, m.PkTypes, " ", ", "), method)
		g.outputGetParent(*m.Parent, o, false, 0)
		g.Printf("\treturn m.%[3]s%[1]s(%[2]s)\n", m.Name, m.ThisKeyNameLower, method)
		g.Printf("}\n\n")
	}
}

func (g *generator) outputValidate(m model) {
	pkNameAndTypes := []string{}
	pkEqualConditions := []string{}
	for _, f := range m.Fields {
		if f.IsPk {
			pkNameAndTypes = append(pkNameAndTypes, f.NameLower+" *"+f.Typ)
			pkEqualConditions = append(pkEqualConditions, "v."+f.Name+" == *"+f.NameLower)
		}
	}
	for _, f := range m.Fields {
		if f.Typ != "string" {
			continue
		}
		if f.Unique {
			if m.Parent == nil {
				g.Printf("func _%[1]s_validate%[2]s(%[3]s string, old%[2]s string) error {\n", m.Name, f.Name, f.NameLower)
			} else {
				g.Printf("func _%[1]s_validate%[2]s(%[3]s string, %[4]s, old%[2]s string) error {\n", m.Name, f.Name, f.NameLower, join(m.Parent.PkNameLowers, m.Parent.PkTypes, " ", ", "))
			}
		} else {
			g.Printf("func _%[1]s_validate%[2]s(%[3]s string) error {\n", m.Name, f.Name, f.NameLower)
		}

		if !f.AllowEmpty {
			g.Printf("\tif %s == \"\" {\n", f.NameLower)
			g.Printf("\t\treturn &sheetdb.EmptyStringError{FieldName: \"%s\"}\n", f.Name)
			g.Printf("\t}\n")
		}

		if f.Unique {
			g.Printf("\tif %[2]s != old%[1]s {\n", f.Name, f.NameLower)
			if m.Parent == nil {
				g.Printf("\t\tif _, ok := _%[1]s_%[2]s_uniqueMap[%[3]s]; ok {\n", m.Name, f.Name, f.NameLower)
			} else {
				g.Printf("\t\tif _, ok := _%[1]s_%[2]s_uniqueMap[%[4]s][%[3]s]; ok {\n", m.Name, f.Name, f.NameLower, strings.Join(m.Parent.PkNameLowers, "]["))
			}
			g.Printf("\t\t\treturn &sheetdb.DuplicationError{FieldName: \"%s\"}\n", f.Name)
			g.Printf("\t\t}\n")
			g.Printf("\t}\n")
		}

		g.Printf("\treturn nil\n")
		g.Printf("}\n\n")
	}
}

func (g *generator) outputParse(m model) {

	for _, f := range m.Fields {
		if f.Typ == "string" {
			continue
		}
		g.Printf("func _%s_parse%s(%s string) (%s, error) {\n", m.Name, f.Name, f.NameLower, f.Typ)

		if f.IsPointer {
			g.Printf("\tvar val %s\n", f.Typ)
			g.Printf("\tif %s != \"\" {\n", f.NameLower)
		}

		switch f.Typ {
		case "bool", "*bool":
			g.Printf("\tv, err := strconv.ParseBool(%s)\n", f.NameLower)
		case "int", "*int":
			g.Printf("\tv, err := strconv.Atoi(%s)\n", f.NameLower)
		case "int8", "*int8":
			g.Printf("\tv, err := strconv.ParseInt(%s, 10, 8)\n", f.NameLower)
		case "int16", "*int16":
			g.Printf("\tv, err := strconv.ParseInt(%s, 10, 16)\n", f.NameLower)
		case "int32", "*int32":
			g.Printf("\tv, err := strconv.ParseInt(%s, 10, 32)\n", f.NameLower)
		case "int64", "*int64":
			g.Printf("\tv, err := strconv.ParseInt(%s, 10, 64)\n", f.NameLower)
		case "uint", "*uint":
			g.Printf("\tv, err := strconv.ParseUint(%s, 10, 64)\n", f.NameLower)
		case "uint8", "*uint8":
			g.Printf("\tv, err := strconv.ParseUint(%s, 10, 8)\n", f.NameLower)
		case "uint16", "*uint16":
			g.Printf("\tv, err := strconv.ParseUint(%s, 10, 16)\n", f.NameLower)
		case "uint32", "*uint32":
			g.Printf("\tv, err := strconv.ParseUint(%s, 10, 32)\n", f.NameLower)
		case "uint64", "*uint64":
			g.Printf("\tv, err := strconv.ParseUint(%s, 10, 64)\n", f.NameLower)
		case "float32", "*float32":
			g.Printf("\tv, err := strconv.ParseFloat(%s, 32)\n", f.NameLower)
		case "float64", "*float64":
			g.Printf("\tv, err := strconv.ParseFloat(%s, 64)\n", f.NameLower)
		default:
			if f.Package == "" {
				g.Printf("\tv, err := New%s(%s)\n", f.TypNonPointer, f.NameLower)
			} else {
				g.Printf("\tv, err := %s.New%s(%s)\n", f.Package, f.TypRaw, f.NameLower)
			}
		}

		g.Printf("\tif err != nil {\n")
		g.Printf("\t\treturn %[2]s, &sheetdb.InvalidValueError{FieldName: \"%[1]s\", Err: err}\n", f.Name, nilValue(f.Typ))
		g.Printf("\t}\n")

		if f.IsPointer {
			switch t := f.TypNonPointer; t {
			case "int8", "int16", "int32",
				"uint", "uint8", "uint16", "uint32",
				"float32", "float64":
				g.Printf("\t\tv2 := %s(v)\n", t)
				g.Printf("\t\tval = &v2\n")
			default:
				g.Printf("\t\tval = &v\n")
			}
			g.Printf("\t}\n")
			g.Printf("\treturn val, nil\n")
		} else {
			switch t := f.Typ; t {
			case "int8", "int16", "int32",
				"uint", "uint8", "uint16", "uint32",
				"float32", "float64":
				g.Printf("\treturn %s(v), nil\n", t)
			default:
				g.Printf("\treturn v, nil\n")
			}
		}

		g.Printf("}\n\n")
	}
}

func (g *generator) outputAsync(m model, o option) {

	// Add
	g.Printf("func (m *%s) _asyncAdd(rowNo int) error {\n", m.Name)
	if !o.TestMode {
		g.Printf("\tdata := []gsheets.UpdateValue{\n")
	} else {
		g.Printf("\t_ = []gsheets.UpdateValue{\n")
	}
	g.Printf("\t\t{\n")
	g.Printf("\t\t\tSheetName: _%s_sheetName,\n", m.Name)
	g.Printf("\t\t\tRowNo:     rowNo,\n")
	g.Printf("\t\t\tValues: []interface{}{\n")

	for _, f := range m.Fields {
		switch f.TypNonPointer {
		case "string", "bool",
			"int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"float32", "float64":
			g.Printf("\t\t\t\tm.%s,\n", f.Name)
		default:
			g.Printf("\t\t\t\tm.%s.String(),\n", f.Name)
		}
	}

	g.Printf("\t\t\t\ttime.Now().UTC(),\n")
	g.Printf("\t\t\t\t\"\",\n")
	g.Printf("\t\t\t},\n")
	g.Printf("\t\t},\n")
	g.Printf("\t}\n")

	if !o.TestMode {
		g.Printf("\treturn %s.AsyncUpdate(data)\n", o.ClientName)
	} else {
		g.Printf("\treturn nil\n")
	}
	g.Printf("}\n\n")

	// Update
	g.Printf("func (m *%s) _asyncUpdate() error {\n", m.Name)
	if !o.TestMode {
		g.Printf("\tdata := []gsheets.UpdateValue{\n")
	} else {
		g.Printf("\t_ = []gsheets.UpdateValue{\n")
	}
	g.Printf("\t\t{\n")
	g.Printf("\t\t\tSheetName: _%s_sheetName,\n", m.Name)
	g.Printf("\t\t\tRowNo:     _%[1]s_rowNoMap[%[2]s],\n", m.Name, strings.Join(prefixes(m.PkNames, "m."), "]["))
	g.Printf("\t\t\tValues: []interface{}{\n")

	for _, f := range m.Fields {
		switch f.TypNonPointer {
		case "string", "bool",
			"int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"float32", "float64":
			g.Printf("\t\t\t\tm.%s,\n", f.Name)
		default:
			g.Printf("\t\t\t\tm.%s.String(),\n", f.Name)
		}
	}

	g.Printf("\t\t\t\ttime.Now().UTC(),\n")
	g.Printf("\t\t\t\t\"\",\n")
	g.Printf("\t\t\t},\n")
	g.Printf("\t\t},\n")
	g.Printf("\t}\n")
	if !o.TestMode {
		g.Printf("\treturn %s.AsyncUpdate(data)\n", o.ClientName)
	} else {
		g.Printf("\treturn nil\n")
	}
	g.Printf("}\n\n")

	// Delete
	g.Printf("func (m *%[1]s) _asyncDelete(%[2]s) error {\n", m.Name, join(m.ChildrenNameLowerPlurals, m.ChildrenNames, " []*", ", "))
	g.Printf("\tnow := time.Now().UTC()\n")
	if !o.TestMode || len(m.Children) > 0 {
		g.Printf("\tdata := []gsheets.UpdateValue{\n")
	} else {
		g.Printf("\t_ = []gsheets.UpdateValue{\n")
	}
	g.Printf("\t\t{\n")
	g.Printf("\t\t\tSheetName: _%s_sheetName,\n", m.Name)
	g.Printf("\t\t\tRowNo:     _%[1]s_rowNoMap[%[2]s],\n", m.Name, strings.Join(prefixes(m.PkNames, "m."), "]["))
	g.Printf("\t\t\tValues: []interface{}{\n")

	for _, f := range m.Fields {
		switch f.TypNonPointer {
		case "string", "bool",
			"int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"float32", "float64":
			g.Printf("\t\t\t\tm.%s,\n", f.Name)
		default:
			g.Printf("\t\t\t\tm.%s.String(),\n", f.Name)
		}
	}

	g.Printf("\t\t\t\tnow,\n")
	g.Printf("\t\t\t\tnow,\n")
	g.Printf("\t\t\t},\n")
	g.Printf("\t\t},\n")
	g.Printf("\t}\n")

	for i, child := range m.Children {
		g.Printf("\tfor _, v := range %s {\n", child.NameLowerPlural)
		g.Printf("\t\tdata = append(data, gsheets.UpdateValue{\n")
		g.Printf("\t\t\tSheetName: _%s_sheetName,\n", child.Name)
		g.Printf("\t\t\tRowNo:     _%s_rowNoMap[%s],\n", child.Name, strings.Join(prefixes(m.Children[i].PkNames, "v."), "]["))
		g.Printf("\t\t\tValues: []interface{}{\n")

		for _, f := range child.Fields {
			switch f.TypNonPointer {
			case "string", "bool",
				"int", "int8", "int16", "int32", "int64",
				"uint", "uint8", "uint16", "uint32", "uint64",
				"float32", "float64":
				g.Printf("\t\t\t\tv.%s,\n", f.Name)
			default:
				g.Printf("\t\t\t\tv.%s.String(),\n", f.Name)
			}
		}

		g.Printf("\t\t\t\tnow,\n")
		g.Printf("\t\t\t\tnow,\n")
		g.Printf("\t\t\t},\n")
		g.Printf("\t\t})\n")
		g.Printf("\t}\n")
	}

	if !o.TestMode {
		g.Printf("\treturn %s.AsyncUpdate(data)\n", o.ClientName)
	} else {
		g.Printf("\treturn nil\n")
	}
	g.Printf("}\n")
}

// Helper

func autoNumbering(pkName, pkType string) bool {
	if pkType == "int" && pkName[len(pkName)-2:] == "ID" {
		return true
	}
	return false
}

func nilValue(t string) string {
	if t == "" {
		return ""
	}
	if t[0] == '*' {
		return "nil"
	}
	switch t {
	case "string":
		return `""`
	case "bool":
		return "false"
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64":
		return "0"
	case "sheetdb.Date", "sheetdb.Datetime":
		return t + "{}"
	}
	// user definition type
	return "v"
}

func prefixes(strs []string, prefix string) []string {
	r := []string{}
	for _, str := range strs {
		r = append(r, prefix+str)
	}
	return r
}

func join(s1, s2 []string, delimiter, separater string) string {
	if len(s1) != len(s2) {
		panic("join functions arguments are invalid: the length of s1 and s2 should be same")
	}
	r := []string{}
	for i := 0; i < len(s1); i++ {
		r = append(r, s1[i]+delimiter+s2[i])
	}
	return strings.Join(r, separater)
}
